org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official

# Maven Central publishing credentials
mavenCentralUsername=
mavenCentralPassword=

# GPG signing — last 8 digits of key ID (gpg --list-secret-keys)
signing.keyId=
# Passphrase set on key creation
signing.password=
# Path to the .gpg keyring file
signing.secretKeyRingFile=
